version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: pkadmin
      POSTGRES_PASSWORD: pkadmin1234
      POSTGRES_DB: pkdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge