version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_network
  # auth:
  #   image: auth_service:latest
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: auth_service
  #   restart: always
  #   environment:
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     DB_HOST: postgres
  #     DB_PORT: ${DB_PORT}
  #   ports:
  #     - "8080:${PORT}"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - auth_network

volumes:
  postgres_data:

networks:
  auth_network:
    driver: bridge